name: ${plugin.name}
main: ${plugin.groupID}.${plugin.name.lower}.${plugin.name}
version: ${plugin.version}
description: ${project.description}
website: ${plugin.url}
authors: [${plugin.author}]
commands:
  ${plugin.name.lower}:
    description: A command for the ${plugin.name} plugin.
    usage: /<command> [args]
